### ISSUE TITLE
new to FastAPI, get {"detail":"Method Not Allowed"} in make.com

### ISSUE THREAD

**Issue by vlad-terin** [JayZeeDesign/researcher-gpt#1]
I'm facing an issue replicating the endpoint part in make.com - getting {"detail":"Method Not Allowed"}

All of the other parts are working as expected. Airtable gets populated, but without the research part.

**Comment by vlad-terin** [comment]
<img width="521" alt="image" src="https://github.com/JayZeeDesign/researcher-gpt/assets/5722749/e72f8c0f-9b1a-4cce-a2a3-c268a8add00a">
what format should it be? am new to coding:)

**Comment by JayZeeDesign** [comment]
Hmm, can you try test the endpoint in postman and see if it works? @vlad-terin

**Comment by vlad-terin** [comment]
Already figured out Jay! Thank you!
